application: evenbrightappraisal
version: 2
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: html/js

- url: /css
  static_dir: html/css

- url: /image
  static_dir: html/image

- url: /font
  static_dir: html/font

- url: /phpinfo
  script: phpinfo.php

- url: /session/.*
  script: php/app/controller/session.php

- url: .*
  script: php/app/controller/home.php
